import { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Avtar from "./component/avtar";
import Slider from "./component/slider";
import Navbar from "./component/navbar";
import Explore from "./component/explore";
import Text from "./component/text";
import Wave from "./component/wave";

const Home: NextPage = () => {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 6000);
  }, []);

  return (
    <div>
      <Head>
        <title>Home | Planet.in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? (
        <div className="loader"></div>
      ) : (
        <>
          <Navbar />
          <hr style={{ visibility: "hidden", marginTop: "5%" }} />
          <Avtar />
          <hr style={{ visibility: "hidden" }} />
          <Explore />
          <hr style={{ visibility: "hidden", marginTop: "3px" }} />
          <Slider />
          <Text />
          <Wave />
        </>
      )}
    </div>
  );
};

export default Home;
